version: '3.8'

services:
  misterpasta-client:
    build:
      context: ./misterpasta.client
      dockerfile: Dockerfile
    container_name: misterpasta-client
    ports:
      - '8080:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true

  misterpasta-server:
    build:
      context: ./MisterPasta.Server
      dockerfile: Dockerfile
    container_name: misterpasta-server
    ports:
      - '8081:5186'
    environment:
      - ASPNETCORE_URLS=http://+:5186
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy

volumes:
  node_modules: