version: '3.8'

services:
  misterpasta-client:
    build:
      context: ./misterpasta.client
      dockerfile: Dockerfile
    container_name: misterpasta-client
    ports:
      - '4200:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0  # Zorgt ervoor dat de Angular-app luistert op alle netwerkinterfaces
    command: "ng serve --host 0.0.0.0"  # Dit zorgt ervoor dat Angular op alle interfaces luistert

  misterpasta-server:
    build:
      context: ./MisterPasta.Server
      dockerfile: Dockerfile
    container_name: misterpasta-server
    ports:
      - '5186:5186'
    environment:
      - ASPNETCORE_URLS=http://+:5186
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy

volumes:
  node_modules: