version: '3.8'

services:
  misterpasta-client:
    build:
      context: ./misterpasta.client
      dockerfile: Dockerfile
    container_name: misterpasta-client
    # Verwijder of commenteer de 'ports' sectie
    # ports:
    #   - '3389:80'
    expose:
      - '80'
    environment:
      - CHOKIDAR_USEPOLLING=true

  misterpasta-server:
    build:
      context: ./MisterPasta.Server
      dockerfile: Dockerfile
    container_name: misterpasta-server
    # Verwijder of commenteer de 'ports' sectie
    # ports:
    #   - '5186:5186'
    expose:
      - '5186'
    environment:
      - ASPNETCORE_URLS=http://+:5186
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy

volumes:
  node_modules:
