// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MisterPasta.Server;

#nullable disable

namespace MisterPasta.Server.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241216131840_ImagesUrlsNameChange")]
    partial class ImagesUrlsNameChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MisterPasta.Server.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1673442635965-34f1b36d8944?w=800&h=600&fit=crop",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1571175534150-72cd2b5a6039?w=800&h=500&fit=crop",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1633337474564-1d9478ca4e2e?w=800&h=500&fit=crop",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1733860532456-3e83dd0b1174?w=800&h=500&fit=crop",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 5,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1726718496691-250e6c3d1a30?w=800&h=500&fit=crop",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 6,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1668618296300-e301f8d2cef9?w=800&h=500&fit=crop",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 7,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1723770033472-0b0452d98225?w=800&h=500&fit=crop",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 8,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1723925079902-9f96f8d32f0d?w=800&h=500&fit=crop",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 9,
                            ImageUrl = "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&h=500&fit=crop",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 10,
                            ImageUrl = "https://images.unsplash.com/photo-1574969903809-3f7a1668ceb0?w=800&h=500&fit=crop",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 11,
                            ImageUrl = "https://images.unsplash.com/photo-1574926053821-79c5e338a933?w=800&h=500&fit=crop",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 12,
                            ImageUrl = "https://images.unsplash.com/photo-1628079251261-624e723b7326?w=800&h=500&fit=crop",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 13,
                            ImageUrl = "https://images.unsplash.com/photo-1630151317550-db97d275ce2d?w=800&h=500&fit=crop",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 14,
                            ImageUrl = "https://images.unsplash.com/photo-1685214743111-f0756f24144c?w=800&h=500&fit=crop",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=500&fit=crop",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 16,
                            ImageUrl = "https://images.unsplash.com/photo-1630151318557-1b2b20cc8cff?w=800&h=500&fit=crop",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 17,
                            ImageUrl = "https://www.allrecipes.com/thmb/LjXULjH7Yd_BeLLTLOlyaDx-xzE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/19402-Quick-And-Easy-Alfredo-Sauce-mfs_002-df1c96e0f9514d2191d0d8ce4c8a9745.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 18,
                            ImageUrl = "https://www.southernliving.com/thmb/zKU_UjR400nWqANM5-0JeJMO2hY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Fettuccine_Alfredo_005-c5f3841f25084c818ff6f8e827154249.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 19,
                            ImageUrl = "https://lemarchebedandbreakfast.com/assets/components/phpthumbof/cache/fettuccine-alfredo.f6caab0d631b41cace65cc930f8dc277.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 20,
                            ImageUrl = "https://www.allrecipes.com/thmb/kegUHrkZqbRFom6G6miHnuqwQvA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Tuna-Alfredo-ca14288bb60b44c98ec50bbd809bd519.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 21,
                            ImageUrl = "https://imag.bonviveur.com/pasta-alla-norma.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 22,
                            ImageUrl = "https://cdn.dagelijksekost.tv/recipes/WaSRK14Q37OzBcZqVzgv/1728244535923_1080x1920?GoogleAccessId=firebase-adminsdk-2hybg%40dagelijkse-kost-prod.iam.gserviceaccount.com&Expires=16725225600&Signature=MCc44WxeBVgKEA6OvRHiNnq6kFJ6fKYmYrXyzlXkCBaDMy%2FVqd5lFDrv8ZessMQRl7xa1uTH8E67BQTV36Sf9fp24Z69fhUM45dpwV2YnJGIPalER3Z8zirCxwh%2F7qMe%2F7VNDfxkC8SVJ364ONMSAlFx8Z5a8yVO8s4IVqNHihXkQ%2F55W1a0gUtBLaxfj%2BPiCfHI6pRMcm6oF8G48CygzZiVFbU8mEYXniuS9tW7MBgy9UlxUupm2TAV5DusQdIp%2FVQ9PC%2BorXGLSGy9MPP4eHCWlEiI3Z9nOTj1DJ8jDulp5rnzQU3D%2FAcCmcfYtMeIAINm0vQqPAmFScOLlT879g%3D%3D",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 23,
                            ImageUrl = "https://thehappyfoodie.co.uk/wp-content/uploads/2021/08/semplice_2_110_img-1372kucwzl_s900x0_c1095x640_l0x234.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 24,
                            ImageUrl = "https://images.dissapore.com/wp-content/uploads/2022/06/pasta-alla-norma-ricetta.jpg?width=1280&height=720&quality=75",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 25,
                            ImageUrl = "https://img.hellofresh.com/f_auto,fl_lossy,h_640,q_auto,w_1200/hellofresh_s3/image/tortellini-in-brodo-358b77fd.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 26,
                            ImageUrl = "https://www.collegeinn.com/sites/default/files/tortellini-en-brodo.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 27,
                            ImageUrl = "https://www.sidechef.com/recipe/51942260-129e-40e4-a66c-d6714b78eda2.jpg?d=1408x1120",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 28,
                            ImageUrl = "https://noseychef.com/wp-content/uploads/2022/11/IMG_9126123.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 29,
                            ImageUrl = "https://smaakmenutie.nl/wp-content/uploads/2018/03/Spaghetti-alla-puttanesca-2-1.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 30,
                            ImageUrl = "https://static01.nyt.com/images/2023/06/29/multimedia/SE-sardine-pasta-puttanesca-czkb/SE-sardine-pasta-puttanesca-czkb-superJumbo.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 31,
                            ImageUrl = "https://alleitaliaanse.nl/pasta/img/puttanesca-cover-16x9.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 32,
                            ImageUrl = "https://chickslovefood.com/resources/uploads/2013/07/Pasta-Puttanesca-van-Jamie_2-scaled.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 33,
                            ImageUrl = "https://www.177milkstreet.com/assets/site/Recipes/_large/Updated-Cacio-e-Pepe.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 34,
                            ImageUrl = "https://assets.epicurious.com/photos/566853fd00de9d2a3815fc8e/master/pass/EP_12012015_dannymeyers_Maialino_pasta.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 35,
                            ImageUrl = "https://www.allesoverolijven.nl/wp-content/uploads/2024/05/Cacio-e-Pepe.jpeg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 36,
                            ImageUrl = "https://sarahpuozzo.com/wp-content/uploads/2018/03/Spaghetti-cacio-e-pepe.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 37,
                            ImageUrl = "https://www.southernliving.com/thmb/qa17Gzd7GwxxgZDz-YZiU6OyiSM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/27722_SUPTskillet_DIGI_43095-a75573c28e5148139e94721f11767a83.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            ImageId = 38,
                            ImageUrl = "https://www.thereciperebel.com/wp-content/uploads/2023/04/pasta-primavera-TRR-10-of-19.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            ImageId = 39,
                            ImageUrl = "https://images.themodernproper.com/billowy-turkey/production/posts/PastaPrimavera_6.jpg?w=1000&h=667&q=82&auto=format&fit=crop&dm=1719193370&s=2c9ffd3e851745fc84daeea036630a40",
                            ProductId = 10
                        },
                        new
                        {
                            ImageId = 40,
                            ImageUrl = "https://talkingmeals.com/wp-content/uploads/2021/05/Pasta-Primavera-Recipe-POST-Plate-Fork-horiz-e1620927923520.jpg",
                            ProductId = 10
                        });
                });

            modelBuilder.Entity("MisterPasta.Server.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsHalal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LargeDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Lange slierten spaghetti in een rijke saus van gehakt, tomaten, en kruiden. Een hartverwarmende klassieker die perfect is voor elke pasta-liefhebber.",
                            IsHalal = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            LargeDescription = "",
                            Name = "Spaghetti Bolognese",
                            Price = 10.99,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Pittige penne met een kruidige tomatensaus.",
                            IsHalal = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            LargeDescription = "",
                            Name = "Lasagne",
                            Price = 12.99,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Romige spaghetti zonder room, maar met een saus van eieren, Parmezaanse kaas en knapperige guanciale. De volle, romige smaak smelt op de tong.",
                            IsHalal = false,
                            IsVegan = false,
                            IsVegetarian = false,
                            LargeDescription = "",
                            Name = "Carbonara",
                            Price = 10.99,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Pittige tomatensaus met knoflook en rode peper geeft deze penne een vurige kick. Ideaal voor wie van een beetje spice houdt!",
                            IsHalal = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            LargeDescription = "",
                            Name = "Penne all’Arrabbiata",
                            Price = 12.99,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Rijke en romige fettuccine, overgoten met een boterachtige Parmezaansaus die smelt in je mond. Het perfecte comfortfood voor een luxueuze traktatie.",
                            IsHalal = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            LargeDescription = "",
                            Name = "Fettuccine Alfredo",
                            Price = 10.99,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Traditionele Siciliaanse pasta met zachte aubergine, tomatensaus en gezouten ricotta. Een verfijnde mix van zoete en hartige smaken.",
                            IsHalal = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            LargeDescription = "",
                            Name = "Pasta alla Norma",
                            Price = 12.99,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Kleine ringvormige pasta gevuld met vlees of kaas, geserveerd in een delicate bouillon. Comfort in een kom, ideaal voor koude dagen.",
                            IsHalal = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            LargeDescription = "",
                            Name = "Tortellini in Brodo",
                            Price = 10.99,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Een smaakvolle mix van tomaten, olijven, kappertjes en ansjovis, die deze pasta een zoute, hartige kick geeft. Perfect voor wie houdt van intense Mediterrane smaken.",
                            IsHalal = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            LargeDescription = "",
                            Name = "Pasta Putanesca",
                            Price = 12.99,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Simpele maar smaakvolle spaghetti met alleen Pecorino Romano en versgemalen zwarte peper. Dit gerecht is de ultieme Italiaanse comfortfood met een zijdezachte, romige saus.",
                            IsHalal = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            LargeDescription = "",
                            Name = "Cacio e Pepe",
                            Price = 10.99,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Lenteachtige pasta met kleurrijke, knapperige groenten zoals paprika, courgette en cherrytomaatjes in een lichte olijfolie-saus. Fris, levendig en vol van smaak!",
                            IsHalal = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            LargeDescription = "",
                            Name = "Pasta Primavera",
                            Price = 12.99,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("MisterPasta.Server.Models.Image", b =>
                {
                    b.HasOne("MisterPasta.Server.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MisterPasta.Server.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
