name: Cypress CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Gebruik alleen ondersteunde Node.js-versies voor Cypress

    steps:
    # Check out de repository
    - uses: actions/checkout@v4

    # Gebruik de juiste versie van Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Installeer dependencies
    - name: Install dependencies
      run: npm ci

    # Build je project indien nodig
    - name: Build the project
      run: npm run build --if-present

    # Installeer Cypress
    - name: Install Cypress
      run: npx cypress install

    # Voer Cypress tests uit
    - name: Run Cypress Tests
      run: npx cypress run
 
