name: Cypress Tests on Hosted Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    # Check out de repository
    - uses: actions/checkout@v4

    # Gebruik de juiste versie van Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Navigeer naar de juiste directory
    - name: Change to misterpasta.client directory
      working-directory: ./PSEMO-MisterPasta/misterpasta.client
      run: echo "Navigated to misterpasta.client directory"

    # Installeer Cypress
    - name: Install Cypress
      working-directory: ./PSEMO-MisterPasta/misterpasta.client
      run: npx cypress install

    # Voer Cypress tests uit op de gehoste applicatie
    - name: Run Cypress Tests
      working-directory: ./PSEMO-MisterPasta/misterpasta.client
      run: npx cypress run
      env:
        CYPRESS_BASE_URL: 'https://145-44-234-98.sslip.io/'
